name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build 
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max,compression=zstd
